modLoader = 'javafml'
loaderVersion = '[4,)'
license = 'MIT'

[[mods]]
modId = 'modscript'
version = '${file.jarVersion}'
displayName = 'ModScript'
description = '''
In-game mod creation platform for Minecraft.
'''
authors = 'ModScript Team'

[[dependencies.modscript]]
modId = 'neoforge'
type = 'required'
versionRange = '[21.1,)'
ordering = 'NONE'
side = 'BOTH'

[[dependencies.modscript]]
modId = 'minecraft'
type = 'required'
versionRange = '[1.21.1,1.22)'
ordering = 'NONE'
side = 'BOTH'
