package com.modscript.project;

import com.google.gson.*;
import com.modscript.registry.ModScriptRegistry;

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.jar.*;
import java.util.zip.*;

public class ModExporter {

    public static exportResult exportToJar(String project, String script, Path outputDir) throws Exception {
        List<String> errors = new ArrayList<>();
        String modId = project.toLowerCase().replaceAll("[^a-z0-9]", "");
        if (modId.isEmpty()) modId = "mymod";

        Path tempDir = Files.createTempDirectory("modscript_export_");
        Path gradleDir = tempDir.resolve("gradle");
        Path srcDir = tempDir.resolve("src/main/java/com/generated/" + modId);
        Path resourcesDir = tempDir.resolve("src/main/resources/META-INF");
        Files.createDirectories(gradleDir);
        Files.createDirectories(srcDir);
        Files.createDirectories(resourcesDir);

        String gradleContent = String.format("""
                plugins {
                    id 'net.neoforged.moddev' version '2.0.124'
                }
                version = '1.0.0'
                base {
                    archivesName = '%s'
                }
                java.toolchain.languageVersion = JavaLanguageVersion.of(21)
                neoForge {
                    version = '21.1.248'
                }
                """, modId);
        Files.writeString(tempDir.resolve("build.gradle"), gradleContent);
        Files.writeString(tempDir.resolve("settings.gradle"), "pluginManagement { repositories { gradlePluginPortal(); maven { url = 'https://maven.neoforged.net/releases' } } }\nrepositories { maven { url = 'https://maven.neoforged.net/releases' } }");

        String modContent = String.format("""
                package com.generated.%s;

                import com.modscript.script.ScriptRuntime;
                import net.neoforged.fml.common.Mod;
                import org.slf4j.Logger;
                import com.mojang.logging.LogUtils;

                @Mod("%s")
                public class %sMod {
                    private static final Logger LOGGER = LogUtils.getLogger();
                    public static final String MODID = "%s";
                    private static final String SCRIPT = %s;

                    public %sMod() {
                        LOGGER.info("Loaded generated mod: %s");
                        try {
                            ScriptRuntime.execute(SCRIPT);
                        } catch (Exception e) {
                            LOGGER.error("Failed to execute ModScript", e);
                        }
                    }
                }
                """, modId, modId, capitalize(modId), modId, quoteScript(script), capitalize(modId), project);
        Files.writeString(srcDir.resolve(capitalize(modId) + "Mod.java"), modContent);

        String modsToml = String.format("""
                modLoader = "javafml"
                loaderVersion = "[4,)"
                license = "MIT"
                [[mods]]
                modId = "%s"
                version = "1.0.0"
                displayName = "%s"
                description = "Generated by ModScript"
                [[dependencies.%s]]
                modId = "neoforge"
                type = "required"
                versionRange = "[21.1,)"
                ordering = "NONE"
                side = "BOTH"
                """, modId, project, modId);
        Files.writeString(resourcesDir.resolve("neoforge.mods.toml"), modsToml);

        String packMcMeta = """
                {
                    "pack": {
                        "description": "Generated ModScript mod",
                        "pack_format": 34
                    }
                }
                """;
        Files.writeString(resourcesDir.resolve("pack.mcmeta"), packMcMeta);

        if (outputDir == null) outputDir = Paths.get(".");
        Files.createDirectories(outputDir);
        Path jarPath = outputDir.resolve(project + "-1.0.0.jar");

        try (JarOutputStream jos = new JarOutputStream(Files.newOutputStream(jarPath))) {
            addDirectoryToJar(jos, tempDir, tempDir);
        }

        Files.writeString(jarPath.resolveSibling(project + "-1.0.0-source.zip"), "");

        cleanupTempDir(tempDir);

        return new exportResult(jarPath.toString(), modId, errors);
    }

    private static void addDirectoryToJar(JarOutputStream jos, Path root, Path current) throws IOException {
        if (Files.isRegularFile(current)) {
            String relative = root.relativize(current).toString().replace('\\', '/');
            jos.putNextEntry(new JarEntry(relative));
            Files.copy(current, jos);
            jos.closeEntry();
        } else if (Files.isDirectory(current)) {
            try (var stream = Files.list(current)) {
                for (Path child : stream.sorted().toList()) {
                    addDirectoryToJar(jos, root, child);
                }
            }
        }
    }

    private static String quoteScript(String script) {
        return "\"" + script.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") + "\"";
    }

    private static String capitalize(String s) {
        if (s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static void cleanupTempDir(Path dir) {
        try {
            Files.walk(dir).sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.deleteIfExists(p); } catch (Exception e) {}
            });
        } catch (Exception e) {}
    }

    public static List<String> validateForExport(String script) {
        List<String> errors = new ArrayList<>();
        if (script == null || script.trim().isEmpty()) { errors.add("Script is empty"); return errors; }
        if (!script.contains("create")) errors.add("No definitions found (use 'create item/block/mob')");
        if (script.length() > 100000) errors.add("Script too large for export (max 100KB)");
        String[] lines = script.split("\n");
        for (int i = 0; i < lines.length; i++) {
            String line = lines[i].trim();
            if (line.startsWith("create") && !line.contains("\"")) {
                errors.add("Line " + (i+1) + ": Missing quoted name");
            }
        }
        return errors;
    }

    public record exportResult(String jarPath, String modId, List<String> errors) {}
}
